name: Gatsby Publish

on:
    push:
        branches:
            - master
            - feature/web

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Install packages
                run: |
                    sudo apt install libudev-dev
            -   uses: actions/checkout@v1
            -   uses: enriikke/gatsby-gh-pages-action@v2
                with:
                    access-token: ${{ secrets.ACCESS_TOKEN }}
                    deploy-branch: gh-pages
